# Generated by Django 2.1.5 on 2019-01-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0001_initial'),
    ]

    operations = [ migrations.DeleteModel(
        name="Popul",
    )
    
    ]
