# Generated by Django 2.1.5 on 2019-01-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0002_auto_20190108_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Population', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt.City')),
            ],
        ),
    ]
