# Generated by Django 2.1.5 on 2019-01-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crt', '0004_auto_20190123_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crt.Worker', to_field='name'),
        ),
    ]
